### ISSUE TITLE
how to exclude entity from dumper ?

### ISSUE THREAD

**Issue by ibasaw** [Spea/SpFixtureDumperBundle#6]
Need to exclude some entities from the dumper, don't see how to do it with this bundle.

**Comment by Spea** [comment]
This is actually not a limitation of the bundle but of the library itself. Currently I just get all metadata which is stored in the EntityManager. To exclude certain entities there has to be some kind of ExclusionStrategy.

I have created an issue in the library (https://github.com/Spea/fixture-dumper/issues/12), but I can not guarantee when I find some spare time to implement this.
